name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: pip install pyinstaller setuptools wheel
    - run: pyinstaller -F -n sr_u2s sr_u2s/__main__.py
    - run: python setup.py sdist bdist_wheel
    - name: Upload exe and wheel
      uses: actions/upload-artifact@v3
      with:
        name: sr_u2s
        path: dist/*
