name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: sr_us2
          path: dist
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
